Cypress.Commands.add('fillMandatoryFieldsAndSubmit', function(){
    cy.get('#firstName')
            .type('John')
    cy.get('#lastName')
            .type('Oakwood')
    cy.get('#email')
            .type('john@oakwood.com')
    cy.get('#open-text-area')
            .type('Teste')
    cy.get('button[type="submit"]')
            .click()
})
